services:
  db:
    image: postgres:alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_DB: "smn"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
  cache:
    image: redis:7.4-rc1-alpine3.20
    restart: unless-stopped
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "1234"]